### ISSUE TITLE
Cleanup of old images appears to be broken

### ISSUE THREAD

**Issue by DrDaveD** [opensciencegrid/cvmfs-singularity-sync#88]
There are currently 2194 images in /cvmfs/singularity.opensciencegrid.org/.images but only 158 names.  Looking at the timestamps of the top level directories of the 2038 images that are not linked from anywhere, they are dating back to February 4 2017.  Is there any attempt to clean out old images?  If so, it is not working.

I think it is clear that old images shouldn't be deleted immediately after they are replaced, but they should get deleted after some period of time, for example a month after they were last current.  Perhaps when an image is replaced the old one can be "touched" to update its modification time and then any unlinked image older than 30 days removed.

**Comment by tpdownes** [comment]
@DrDaveD I think we should consider the case where multiple tags points to the same image. It would be reasonable to publish both "latest" and "vX.Y.Z" pointing to the same underlying image.

I'm not sure if the code, as written does this. I'm not sure if [my publisher](https://github.com/lscsoft/cvmfs-docker-worker) does. But, I think it should be considered since multiple tags pointing to a single Docker image is reasonable/encouraged practice.

In that instance, I think you'd need to either search the filesystem for symlinks or maintain a DB of such links before "garbage collection." The publisher I wrote keeps the images closer in the directory structure to their symlinked tagged directory so the filesystem search seems more plausible.

**Comment by DrDaveD** [comment]
I think my suggested algorithm covers the case of multiple links.  It just cleans up images that haven't had any links for at least 30 days.

**Comment by bbockelm** [comment]
Hi @DrDaveD -

I think your algorithm sounds fine.  I'm not sure when I'll be able to schedule the work though -- will discuss with Marian and Derek today.

If there isn't any action in two weeks, please send a ping to this ticket.

Brian

**Comment by bbockelm** [comment]
Ah - mentioning @djw8605 and @zvada so they are subscribed to ticket updates.

**Comment by tpdownes** [comment]
FWIW, I have taken the approach of mapping from images to tags in `/cvmfs/ligo-containers.opensciencegrid.org/.publications.json`.

https://github.com/lscsoft/cvmfs-docker-worker/blob/master/cvmfs/publisher.py#L77
https://github.com/lscsoft/cvmfs-docker-worker/blob/master/cvmfs/publisher.py#L94

The idea being that when an image is mapped to the empty list, it can be deleted. An initial mapping can be obtained with commands like:

```
find /cvmfs/singularity.opensciencegrid.org/.images/ -maxdepth 2 -type d -regextype egrep -regex '.*/[0-9a-f]{62}' 2>/dev/null > images_to_map
while read image; do find /cvmfs/singularity.opensciencegrid.org -maxdepth 3 -lname $image -printf "\"$image\": [\n  \"%p\"\n],\n"  2>/dev/null; done < images_to_map
```

You have to format the JSON a little bit but using this method I was able to create a machine-readable file that identified 156 active mappings. I didn't see any examples of images mapped multiple times, but maybe that reflects my code rather than the actual state of affairs.

Obviously, you can ignore this approach if you like, but I really do want to try to identify common publishing problems and solve them generically.

**Comment by DrDaveD** [comment]
It's been more than 2 weeks, so I am sending a ping to this ticket as @bbockelm requested.  @jblomer asked about the cleanup in today's wlcg-containers meeting.

**Comment by djw8605** [comment]
I read this issue.  In #94 we added cleanup.  It's very similar to your code @tpdownes, where you kept a json of links.  We simply keep json file of all of the missing links, which will hopefully soon be deleted.

**Comment by DrDaveD** [comment]
@djw8605 When can we expect to see fewer images in /cvmfs/singularity.opensciencegrid.org/.images?  There's 2302 now, no decrease.

**Comment by djw8605** [comment]
There’s a delay of 2 days. And it was deployed yesterday. I would expect the images to be deleted tomorrow. 

-Derek

**Comment by DrDaveD** [comment]
Good, today there are only 160 images.

**Comment by djw8605** [comment]
Now we wait for CVMFS garbage collection. 

-Derek
